force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial_Account</label>
    <nameField>
        <displayFormat>FA-{000000}</displayFormat>
        <label>Financial_Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial_Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest_Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Total_Interest__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total_Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InterestCalculationBatch.cls
global class InterestCalculationBatch implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Loan_Amount__c, Interest_Rate__c, Total_Interest__c FROM Financial_Account__c'
        );
    }

    global void execute(Database.BatchableContext bc, List<Financial_Account__c> scope) {

        for (Financial_Account__c acc : scope) {

            if (acc.Loan_Amount__c != null && acc.Interest_Rate__c != null) {

                Decimal dailyInterest = (acc.Loan_Amount__c * acc.Interest_Rate__c) / 100 / 365;

                acc.Total_Interest__c =
                    (acc.Total_Interest__c == null ? 0 : acc.Total_Interest__c) + dailyInterest;
            }
        }

        update scope;
    }

    global void finish(Database.BatchableContext bc) {}
}